//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftReportViewerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingAndActiveProject
    {
        public int Code { get; set; }
        public string Name { get; set; }
        public string Project_Title { get; set; }
        public string Tasks_Name { get; set; }
        public Nullable<System.DateTime> Estimation_Date { get; set; }
        public string Developer_Name { get; set; }
    }
}
